### ISSUE TITLE
Error in errorlog method

### ISSUE THREAD

**Issue by simpsora** [yassineaboukir/sublert#3]
I encountered this error this morning.  It looks like `error` is a class and not a string, but I haven't had a chance to dig in any deeper yet.  Note that nothing was logged to `errorlogging_webhook`.

Python 3.7.2.

```
[!] We encountered a small issue, please check error logging slack channel.
--
  | Traceback (most recent call last):
  | File "sublert.py", line 444, in <module>
  | posting_to_slack(new_subdomains, False, None)
  | File "sublert.py", line 384, in posting_to_slack
  | slack(data)
  | File "sublert.py", line 109, in slack
  | errorlog(errorlog, enable_logging)
  | File "sublert.py", line 148, in errorlog
  | slack_data = {'text': '```' + error + '```'}
  | TypeError: can only concatenate str (not "function") to str
```

**Comment by yassineaboukir** [comment]
You're correct! your fix should resolve it, thank you!
